# Clippy configuration
# For a list of all lints, see https://rust-lang.github.io/rust-clippy/master/index.html

# Allow some common patterns that might be useful in Tauri apps
# (Adjust based on project preferences)
"clippy::module-name-repetitions" = "allow"
"clippy::missing-errors-doc" = "allow"
"clippy::missing-panics-doc" = "allow"
"clippy::cast-possible-truncation" = "allow"
